### ISSUE TITLE
Compatibility with lsio / mariadb

### ISSUE THREAD

**Issue by nishantbb** [linuxserver/docker-clarkson#15]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Desired Behavior

If it's possible for the mariadb container to be updated to the version required by Clarkson container, then two LSIO containers could be used together.

## Current Behavior

LSIO docker-clarkson container requires mysql 5.7. 
Current mysql version used by LSIO mariadb container is 5.6.x
This may be the cause of some problems.

## Alternatives Considered

Use mysql container / database independent of LSIO. If this is the current solution, please let me know.
I am a fan of the LSIO containers and ARM offerings. I use mariadb for a few other LSIO containers, and they work well.

**Comment by aptalca** [comment]
I can't comment on clarkson and mariadb, but with regards to the versions, mariadb version of the arm32 latest build is behind because mariadb does not publish arm32 binaries so we pull from the ubuntu repo.

However, we now publish an alpine tag for the mariadb image and that one has up to date versions on all arches.

**Comment by nishantbb** [comment]
Thanks for the info. I will test out versioning with the different tags.
